### ISSUE TITLE
Crashes after a few Seconds.

### ISSUE THREAD

**Issue by emlinhax** [sitesgithub/dncc#1]
After I open the Program, it checks a few codes, and then crashes without an error.

**Comment by sitesgithub** [comment]
Please give me the logs of the error, thanks.

**Comment by BlaNKtext** [comment]
i edited the code and fixed it here becuase i was having the same problem
https://github.com/BlaNKtext/Discord-Nitro-code-gen-checker

**Comment by sitesgithub** [comment]
i don't care this is dead
