### ISSUE TITLE
(node:47411) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added to [Request]. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by DefectiveVortex** [sitesgithub/dncc#6]
The whole code is working but I get this warning very every 2 seconds, '(node:47411) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added to [Request]. Use emitter.setMaxListeners() to increase limit'. Is there a way to fix this somehow?

**Comment by NotSwaraj** [comment]
Lower the emitters down bruh, Dm me if you cant do that S_waraj#7777

**Comment by AzaelMew** [comment]
Yom having the same issue, could you hmu on discord Azael#2282, need help with doing that

**Comment by NotSwaraj** [comment]
> Yom having the same issue, could you hmu on discord Azael#2282, need help with doing that

Sent a fr req, seems that your dms are closed so i cant dm you

**Comment by mthuilot** [comment]
Same code is working but it shows  '(node:47411) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added to [Request]. Use emitter.setMaxListeners() to increase limit'.

**Comment by tzt345** [comment]
That is a connection error

**Comment by sitesgithub** [comment]
i don't care this is dead
